import {text,candidate,allowed} from './shared.mjs';
const H={headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36','accept-language':'zh-TW,zh;q=0.9,en;q=0.8'}};
export const SOURCES=[
 {platform:'Netflix',urls:['https://about.netflix.com/zh_tw/new-to-watch','https://about.netflix.com/zh_tw/newsroom']},
 {platform:'Disney+',urls:['https://www.disney.com.tw/disneyplus-articles']},
 {platform:'iQIYI',urls:['https://www.iq.com/?lang=zh_tw','https://pca.iq.com/?lang=zh_tw','https://www.iq.com/ranking?lang=zh_tw','https://www.iq.com/newOnline?lang=zh_tw','https://www.iq.com/drama?lang=zh_tw','https://www.iq.com/variety-show?lang=zh_tw']},
 {platform:'friDay影音',urls:['https://video.friday.tw/drama','https://video.friday.tw/show']},
 {platform:'Hami Video',urls:['https://hamivideo.hinet.net/index.do']},
 {platform:'MyVideo',urls:['https://www.myvideo.net.tw/drama/','https://www.myvideo.net.tw/program/']},
 {platform:'LINE TV',urls:['https://www.linetv.tw/channel/1','https://www.linetv.tw/channel/2']}
];
function isoDate(y,m,d){m=+m;d=+d;if(m<1||m>12||d<1||d>31)return null;return`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function explicitRelease(s,year){const n=String(s).replace(/\s+/g,' ');const full=n.match(/(20\d{2})[年/.\-](\d{1,2})[月/.\-](\d{1,2})日?[^。！？\n]{0,35}?(?:上線|上架|首播|開播|播出|登場|定檔)|(?:上線|上架|首播|開播|播出|登場|定檔)[^。！？\n]{0,35}?(20\d{2})[年/.\-](\d{1,2})[月/.\-](\d{1,2})日?/i);if(full){const a=full[1]?full.slice(1,4):full.slice(4,7);return isoDate(a[0],a[1],a[2])}const ps=[/(?:上線|上架|首播|開播|播出|登場|定檔)[^。！？\n]{0,35}?(\d{1,2})[月/.\-](\d{1,2})日?/i,/(\d{1,2})[月/.\-](\d{1,2})日?[^。！？\n]{0,35}?(?:上線|上架|首播|開播|播出|登場|定檔)/i];for(const p of ps){const m=n.match(p);if(m)return isoDate(year,m[1],m[2])}return null}
function typeNear(s){if(/綜藝|實境|真人秀|選秀|variety|reality|節目/i.test(s))return'綜藝';if(/影集|戲劇|劇集|陸劇|韓劇|台劇|日劇|美劇|series|drama|電視劇/i.test(s))return'戲劇';return''}
function titleFromAnchor(a){return text(a).replace(/(?:立即觀看|線上看|播放|更多|詳情|預告|即將上線|新上架|預約|在 Netflix 上觀賞|Play on Netflix)/gi,'').trim()}
function rejectNews(title,around){const s=`${title} ${around}`;return /獲獎|入圍|提名|排行榜|TOP\s*10|收視|觀看時數|記者會|發布會|預告曝光|海報曝光|演員陣容|開鏡|殺青|製作消息|新聞專區/i.test(s)&&!/定檔|上線|上架|首播|開播|播出|登場/i.test(s)}
function parseNetflixCatalog(url,html){const s=text(html),out=[],re=/(.{2,80}?)(20\d{2})[/.\-](\d{1,2})[/.\-](\d{1,2})(?:在 Netflix 上觀賞|Play on Netflix)/g;let m;while((m=re.exec(s))){let title=m[1].trim().split(/(?:全部|電影|影集|特輯|遊戲|→)/).pop().trim();title=title.replace(/^.*?(?=[\p{L}\p{N}])/u,'').trim();if(title.length<2||title.length>70||!allowed('',title))continue;const around=s.slice(Math.max(0,m.index-120),Math.min(s.length,re.lastIndex+120));if(/體壇祕話|轉捩時刻|紀錄片|documentary/i.test(around))continue;out.push(candidate({platform:'Netflix',title,url,date:isoDate(m[2],m[3],m[4]),type:'戲劇',verified:true,verificationMethod:'official_catalog',note:'Netflix 官方 New to Watch 直接列出作品與上線日期。',claimText:m[0]}))}return out}
function parseDisney(url,html,year){const out=[],re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const raw=titleFromAnchor(m[2]);const tm=raw.match(/Disney\+《([^》]+)》/);if(!tm)continue;const title=tm[1],around=text(html.slice(Math.max(0,m.index-400),Math.min(html.length,re.lastIndex+400)));if(/電影|動畫|皮克斯|漫威特輯/.test(around)&&!/影集|韓劇|陸劇|日劇|戲劇/.test(around))continue;const date=explicitRelease(around,year);let href=m[1];try{href=new URL(href,url).href}catch{};if(date)out.push(candidate({platform:'Disney+',title,url:href,date,type:typeNear(around)||'戲劇',verified:true,verificationMethod:'official_article',note:'Disney+ 官方文章區塊包含作品與明確上線資訊。',claimText:around}));else out.push(candidate({platform:'Disney+',title,url:href,type:typeNear(around)||'戲劇',note:'Disney+ 官方文章已辨識作品，但列表未提供可安全判定的上線日，保留待確認。',claimText:around}))}return out}
function parseIqiyi(url,html,year){const s=text(html),out=[],forced=url.includes('variety-show')?'綜藝':url.includes('/drama')?'戲劇':'';const re=/(.{0,60}?)(\d{1,2})[/.月-](\d{1,2})日?\s*(?:上線|首播|開播|播出|登場)/g;let m;while((m=re.exec(s))){const date=isoDate(year,m[2],m[3]);let title=m[1].trim().split(/\s+/).pop()||'';title=title.replace(/^(?:大結局|新片上線|即將上線|更多內容|愛奇藝新劇)+/,'').replace(/(?:大結局|更新至\d+集|\d+集全)$/,'').trim();const context=s.slice(Math.max(0,m.index-150),Math.min(s.length,re.lastIndex+150)),type=forced||typeNear(context);if(!date||!type||title.length<2||title.length>40||!allowed(type,`${title} ${context}`))continue;out.push(candidate({platform:'iQIYI',title,url,date,type,verified:true,verificationMethod:'official_explicit',note:'iQIYI 官方頁面直接顯示作品名稱與播出日期。',claimText:m[0]}))}return out}
function parseGeneric(platform,url,html,year){const out=[],re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const title=titleFromAnchor(m[2]);if(title.length<2||title.length>80)continue;const around=text(html.slice(Math.max(0,m.index-350),Math.min(html.length,re.lastIndex+350)));if(rejectNews(title,around)||!allowed('',`${title} ${around}`))continue;const type=url.includes('/drama')||url.includes('/channel/1')?'戲劇':url.includes('/show')||url.includes('/program')||url.includes('/channel/2')?'綜藝':typeNear(around),date=explicitRelease(around,year);let href=m[1];try{href=new URL(href,url).href}catch{};if(date&&type)out.push(candidate({platform,title,url:href,date,type,verified:true,verificationMethod:'official_explicit',note:'平台官方內容頁直接提供作品類型與上線／首播日期。',claimText:around}));else if(type&&/即將上線|新片上線|跟播中|現正熱播|預約|新上架/i.test(around))out.push(candidate({platform,title,url:href,type,note:'已在官方內容頁辨識作品，但缺少可安全判定的首播日期。',claimText:around}))}return out}
function parse(platform,url,html,year){if(platform==='Netflix'&&url.includes('/new-to-watch'))return parseNetflixCatalog(url,html);if(platform==='Disney+')return parseDisney(url,html,year);if(platform==='iQIYI')return parseIqiyi(url,html,year);return parseGeneric(platform,url,html,year)}
export async function scanPlatform(source,year){const all=[];for(const url of source.urls){try{const r=await fetch(url,H),html=await r.text();if(r.ok)all.push(...parse(source.platform,url,html,year))}catch(e){console.log('source error',source.platform,url,String(e?.message||e))}}const seen=new Set();return all.filter(x=>{const k=`${x.platform}|${x.title}|${x.release_date||''}`;if(seen.has(k))return false;seen.add(k);return true})}
