import {text,candidate,allowed} from './shared.mjs';
const H={headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36','accept-language':'zh-TW,zh;q=0.9,en;q=0.8'}};
export const SOURCES=[
 {platform:'Netflix',official:{website:['https://about.netflix.com/zh_tw/new-to-watch','https://about.netflix.com/zh_tw/newsroom'],facebook:[],instagram:[]}},
 {platform:'Disney+',official:{website:['https://www.disney.com.tw/disneyplus-articles'],facebook:[],instagram:[]}},
 {platform:'iQIYI',official:{website:['https://www.iq.com/newOnline?lang=zh_tw','https://www.iq.com/drama?lang=zh_tw','https://www.iq.com/variety-show?lang=zh_tw'],facebook:[],instagram:[]}},
 {platform:'friDay影音',official:{website:['https://video.friday.tw/drama','https://video.friday.tw/show'],facebook:[],instagram:[]}},
 {platform:'Hami Video',official:{website:['https://hamivideo.hinet.net/index.do'],facebook:[],instagram:[]}},
 {platform:'MyVideo',official:{website:['https://www.myvideo.net.tw/drama/','https://www.myvideo.net.tw/program/'],facebook:[],instagram:[]}},
 {platform:'LINE TV',official:{website:['https://www.linetv.tw/channel/1','https://www.linetv.tw/channel/2'],facebook:[],instagram:[]}}
];
function isoDate(y,m,d){m=+m;d=+d;if(m<1||m>12||d<1||d>31)return null;const x=new Date(Date.UTC(+y,m-1,d));return x.getUTCMonth()===m-1&&x.getUTCDate()===d?`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`:null}
function explicitRelease(s,year){const n=String(s).replace(/\s+/g,' '),verbs='上線|上架|首播|開播|播出|登場|定檔|全集上線|正式上線';let m=n.match(new RegExp(`(20\\d{2})[年/.\\-](\\d{1,2})[月/.\\-](\\d{1,2})日?[^。！？\\n]{0,45}?(?:${verbs})|(?:${verbs})[^。！？\\n]{0,45}?(20\\d{2})[年/.\\-](\\d{1,2})[月/.\\-](\\d{1,2})日?`,'i'));if(m){const a=m[1]?m.slice(1,4):m.slice(4,7);return isoDate(a[0],a[1],a[2])}for(const p of [new RegExp(`(?:${verbs})[^。！？\\n]{0,45}?(\\d{1,2})[月/.\\-](\\d{1,2})日?`,'i'),new RegExp(`(\\d{1,2})[月/.\\-](\\d{1,2})日?[^。！？\\n]{0,45}?(?:${verbs})`,'i')]){m=n.match(p);if(m)return isoDate(year,m[1],m[2])}return null}
function typeNear(s){if(/綜藝|實境|真人秀|選秀|variety|reality|節目/i.test(s))return'綜藝';if(/影集|戲劇|劇集|陸劇|韓劇|台劇|日劇|美劇|series|drama|電視劇/i.test(s))return'戲劇';return''}
function titleFromAnchor(a){return text(a).replace(/(?:立即觀看|線上看|播放|更多|詳情|預告|即將上線|新上架|預約|在 Netflix 上觀賞|Play on Netflix)/gi,'').trim()}
function reject(title,around){const s=`${title} ${around}`;return /獲獎|入圍|提名|排行榜|TOP\s*10|收視|觀看時數|記者會|發布會|預告曝光|海報曝光|演員陣容|開鏡|殺青|製作消息|新聞專區/i.test(s)&&!/定檔|上線|上架|首播|開播|播出|登場/i.test(s)}
function parseNetflix(url,html){if(!url.includes('/new-to-watch'))return[];const s=text(html),out=[],re=/(.{2,80}?)(20\d{2})[/.\-](\d{1,2})[/.\-](\d{1,2})(?:在 Netflix 上觀賞|Play on Netflix)/g;let m;while((m=re.exec(s))){let title=m[1].trim().split(/(?:全部|電影|影集|特輯|遊戲|→)/).pop().trim();const around=s.slice(Math.max(0,m.index-140),Math.min(s.length,re.lastIndex+140));if(title.length<2||title.length>70||!allowed('',title)||/紀錄片|documentary/i.test(around))continue;out.push(candidate({platform:'Netflix',title,url,date:isoDate(m[2],m[3],m[4]),type:'戲劇',verified:true,verificationMethod:'official_catalog',claimText:m[0],note:'Netflix 官方 New to Watch 明列作品與上線日期。'}))}return out}
function parseAnchors(platform,url,html,year){const out=[],re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){let title=titleFromAnchor(m[2]);if(platform==='Disney+'){const t=title.match(/Disney\+《([^》]+)》/);if(t)title=t[1]}if(title.length<2||title.length>80)continue;const around=text(html.slice(Math.max(0,m.index-450),Math.min(html.length,re.lastIndex+450)));if(reject(title,around)||!allowed('',`${title} ${around}`))continue;const forced=url.includes('/drama')||url.includes('/channel/1')?'戲劇':url.includes('/show')||url.includes('/program')||url.includes('/channel/2')?'綜藝':'',type=forced||typeNear(around),date=explicitRelease(around,year);if(!type)continue;let href=m[1];try{href=new URL(href,url).href}catch{};if(date)out.push(candidate({platform,title,url:href,date,type,verified:true,verificationMethod:'official_explicit',claimText:around,note:'官方頁面同一內容區塊包含作品與明確播出日期。'}));else if(/即將上線|新片上線|跟播中|現正熱播|預約|新上架|即將播出/i.test(around))out.push(candidate({platform,title,url:href,type,claimText:around,note:'官方來源已辨識作品，但沒有安全可判定的上架日期。'}))}return out}
function parse(platform,url,html,year){return platform==='Netflix'?parseNetflix(url,html):parseAnchors(platform,url,html,year)}
async function fetchSource(platform,kind,url,year){const started=Date.now();try{const r=await fetch(url,H),html=await r.text();if(!r.ok)return{items:[],health:{kind,url,status:`http_${r.status}`,duration_ms:Date.now()-started}};return{items:parse(platform,url,html,year),health:{kind,url,status:'ok',duration_ms:Date.now()-started}}}catch(e){return{items:[],health:{kind,url,status:'error',error:String(e?.message||e),duration_ms:Date.now()-started}}}}
export async function scanPlatform(source,year){const all=[],health=[];for(const [kind,urls] of Object.entries(source.official)){for(const url of urls){const got=await fetchSource(source.platform,kind,url,year);all.push(...got.items);health.push(got.health)}}const seen=new Set(),items=all.filter(x=>{const k=`${x.platform}|${x.title}|${x.release_date||''}`;if(seen.has(k))return false;seen.add(k);return true});return{items,health}}
