export const now=()=>new Date().toISOString();
export function text(html=''){return String(html).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
export function twToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export function iso(y,m,d){return `${String(y).padStart(4,'0')}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
export function add(date,n){const d=new Date(`${date}T12:00:00+08:00`);d.setDate(d.getDate()+n);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
export function monday(date){const d=new Date(`${date}T12:00:00+08:00`),w=d.getDay();return add(date,w===0?-6:1-w)}
export function range(input){const today=twToday(),y=+today.slice(0,4),r=String(input||'這週').trim().replace(/\s+/g,'').replace(/[－—–~至]/g,'～');if(r==='這週'||r==='本週')return{start:monday(today),end:today,label:'這週'};if(r==='上週'){const e=add(monday(today),-1);return{start:add(e,-6),end:e,label:'上週'}};let m=r.match(/^(\d{4})\/(\d{1,2})\/(\d{1,2})～(\d{4})\/(\d{1,2})\/(\d{1,2})$/);if(m)return{start:iso(+m[1],+m[2],+m[3]),end:iso(+m[4],+m[5],+m[6]),label:r};m=r.match(/^(\d{1,2})\/(\d{1,2})～(\d{1,2})\/(\d{1,2})$/);if(m)return{start:iso(y,+m[1],+m[2]),end:iso(y,+m[3],+m[4]),label:r};m=r.match(/^(\d{4})\/(\d{1,2})\/(\d{1,2})$/);if(m)return{start:iso(+m[1],+m[2],+m[3]),end:today,label:`${r}～今天`};m=r.match(/^(\d{1,2})\/(\d{1,2})$/);if(m)return{start:iso(y,+m[1],+m[2]),end:today,label:`${r}～今天`};return{start:monday(today),end:today,label:'這週'}}
export function exclusive(s=''){const n=String(s).replace(/\s+/g,' ');if(/獨家專訪|獨家訪問|獨家花絮|獨家片段|獨家預告|獨家搶先看|VIP\s*獨家搶先|會員獨家/i.test(n))return{status:'unknown',claim:''};const m=n.match(/全球獨家|全台獨家|全網獨播|全網獨家|全台獨播|獨家全集上線|獨家播出|獨家上線|平台獨家|\bonly\s+on\b|\bexclusive\b|僅在.{0,30}(?:播出|上線|觀看)|只在.{0,30}(?:播出|上線|觀看)/i);return m?{status:'true',claim:m[0]}:{status:'unknown',claim:''}}
export function allowed(type='',title=''){const s=`${type} ${title}`;return !/電影|動畫|動漫|短劇|微短劇|紀錄片|演唱會|直播|特輯|體育|賽事|遊戲/i.test(s)}
export function candidate({platform,title,url,date=null,type='',note='',source='官方網站',claimText=''}){const ex=exclusive(claimText);return{id:`${platform}-${encodeURIComponent(title)}-${date||'pending'}`,title,platform,content_type:type,region:'',release_date:date,release_kind:date?'上架':'待確認',episode_info:'',exclusive_status:ex.status,exclusive_claim_text:ex.claim,verification_status:date&&type?'verified':'pending',source_label:`${platform} ${source}`,source_url:url,source_published_at:null,fetched_at:now(),review_note:note}}
