const PLATFORMS=['iQIYI','friDay影音','Netflix','Disney+','Hami Video','MyVideo','LINE TV'];
const CFG={
'iQIYI':{name:'愛奇藝',urls:['https://www.iq.com/newOnline?lang=zh_tw','https://www.iq.com/drama?lang=zh_tw','https://www.iq.com/variety-show?lang=zh_tw']},
'friDay影音':{name:'friDay影音',urls:['https://video.friday.tw/drama','https://video.friday.tw/show']},
'Netflix':{name:'Netflix',urls:['https://about.netflix.com/zh_tw/new-to-watch','https://about.netflix.com/zh_tw/newsroom']},
'Disney+':{name:'Disney+',urls:['https://www.disney.com.tw/disneyplus-articles']},
'Hami Video':{name:'Hami Video',urls:['https://hamivideo.hinet.net/index.do']},
'MyVideo':{name:'MyVideo',urls:['https://www.myvideo.net.tw/drama/','https://www.myvideo.net.tw/program/']},
'LINE TV':{name:'LINE TV',urls:['https://www.linetv.tw/channel/1','https://www.linetv.tw/channel/2']}}
};
const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}});
const fmt=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(d),today=()=>fmt(new Date());
const add=(s,n)=>{let d=new Date(s+'T12:00:00+08:00');d.setDate(d.getDate()+n);return fmt(d)},mon=s=>{let d=new Date(s+'T12:00:00+08:00'),w=d.getDay();return add(s,w===0?-6:1-w)};
function range(v='近30天'){let t=today(),y=t.slice(0,4),s=String(v).trim().replace(/\s+/g,'').replace(/[－—–~至]/g,'～');if(s==='今天')return{start:t,end:t,label:'今天'};if(/^(近|最近)?(30天|一個月|1個月)$/.test(s))return{start:add(t,-29),end:t,label:'近30天'};if(/^(這週|本週)$/.test(s))return{start:mon(t),end:t,label:'這週'};if(s==='上週'){let e=add(mon(t),-1);return{start:add(e,-6),end:e,label:'上週'}}let m=s.match(/^(20\d{2})\/(\d{1,2})\/(\d{1,2})$/);if(m)return{start:`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`,end:t,label:s+'～今天'};m=s.match(/^(\d{1,2})\/(\d{1,2})～(\d{1,2})\/(\d{1,2})$/);if(m)return{start:`${y}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`,end:`${y}-${m[3].padStart(2,'0')}-${m[4].padStart(2,'0')}`,label:s};m=s.match(/^(\d{1,2})\/(\d{1,2})$/);return m?{start:`${y}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`,end:t,label:s+'～今天'}:{start:add(t,-29),end:t,label:'近30天'}}
function dec(s=''){return s.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n))}
function strip(h=''){return dec(h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')).trim()}
function titleOf(s=''){s=strip(s);let m=s.match(/[《〈「『]([^》〉」』]{2,60})[》〉」』]/);if(m)return m[1].trim();return''}
function dateOf(s,year=today().slice(0,4)){const V='上線|上架|首播|開播|播出|登場|定檔|全集上線|正式上線|正式開播|開更|推出|收看';let a=[new RegExp('(20\\d{2})[年/.\\-](\\d{1,2})[月/.\\-](\\d{1,2})日?[^。！？]{0,55}('+V+')'),new RegExp('(\\d{1,2})[月/.\\-](\\d{1,2})日?[^。！？]{0,55}('+V+')'),new RegExp('('+V+')[^。！？]{0,45}(20\\d{2})[年/.\\-](\\d{1,2})[月/.\\-](\\d{1,2})日?'),new RegExp('('+V+')[^。！？]{0,45}(\\d{1,2})[月/.\\-](\\d{1,2})日?')],m=s.match(a[0]);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=s.match(a[1]);if(m)return`${year}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;m=s.match(a[2]);if(m)return`${m[2]}-${m[3].padStart(2,'0')}-${m[4].padStart(2,'0')}`;m=s.match(a[3]);return m?`${year}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:null}
function typeOf(s){if(/綜藝|實境|真人秀|選秀|variety|reality/i.test(s))return'綜藝';if(/影集|戲劇|劇集|陸劇|韓劇|台劇|日劇|美劇|series|drama|連續劇/i.test(s))return'戲劇';return''}
const allowed=s=>!/電影|動畫|動漫|短劇|微短劇|紀錄片|演唱會|直播|特輯|體育|賽事|遊戲|電影版/i.test(s);
function excl(s){if(/獨家專訪|獨家花絮|獨家預告|獨家片段|VIP.{0,8}獨家.{0,8}搶先看/i.test(s))return'';let m=s.match(/全台獨家|全球獨家|全網獨播|全網獨家|獨家播出|獨家上線|Only on\s+[^。！？,，]{1,30}|Exclusive\s+on\s+[^。！？,，]{1,30}|僅在[^。！？,，]{1,20}(?:播出|上線)/i);return m?m[0]:''}
function published(h){let m=h.match(/(?:article:published_time|datePublished)[^>]{0,160}(?:content=|:)["']?([^"'<>,} ]{8,35})/i);return m?m[1]:null}
function mk(p,t,d,ty,u,text,kind='website',pub=null){let c=excl(text);return{id:`${p}-${encodeURIComponent(t)}-${d}`,title:t,platform:p,content_type:ty,region:'台灣',release_date:d,release_kind:'上架',episode_info:'',exclusive_status:c?'true':'unknown',exclusive_claim_text:c,verification_status:'verified',verification_method:'official_explicit',source_label:`${p} 官方${kind==='social'?'社群':'網站'}`,source_url:u,source_published_at:pub,fetched_at:new Date().toISOString(),review_note:'官方來源明確包含作品、類型與上線日期。',evidence:[{kind,label:`${p} 官方來源`,url:u,release_date:d,claim_text:text.slice(0,600)}]}}
function parsePage(p,u,h){let text=strip(h),t=titleOf(text),d=dateOf(text),ty=typeOf(text);if(!t||!d||!ty||!allowed(t+' '+text))return[];if(/獲獎|入圍|提名|排行榜|記者會|專訪/.test(t)&&!/(上線|上架|首播|開播|定檔)/.test(text))return[];return[mk(p,t,d,ty,u,text,'website',published(h))]}
function pageLinks(base,h){let out=new Set(),re=/<a\b[^>]*href=["']([^"']+)["']/gi,m,b=new URL(base);while((m=re.exec(h))){try{let u=new URL(dec(m[1]),base);if(u.hostname===b.hostname&&/\/news\/|\/article|\/program|\/drama|\/show|\/detail|\/content|\/play|\/video/i.test(u.pathname))out.add(u.href)}catch{}}return[...out].slice(0,14)}
async function get(u){let r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36','accept-language':'zh-TW,zh;q=0.9,en;q=0.5'}});if(!r.ok)throw Error(String(r.status));return r.text()}
async function render(env,u){if(!env.BROWSER)return'';try{let r=await env.BROWSER.quickAction('content',{url:u,gotoOptions:{waitUntil:'domcontentloaded',timeout:12000}});return await r.text()}catch{return''}}
function bingLinks(h,hosts){let out=new Set(),re=/<li[^>]+class=["'][^"']*b_algo[^"']*["'][\s\S]*?<h2[^>]*>\s*<a[^>]+href=["']([^"']+)/gi,m;while((m=re.exec(h))){try{let u=new URL(dec(m[1]));if(hosts.some(x=>u.hostname===x||u.hostname.endsWith('.'+x)))out.add(u.href)}catch{}}return[...out]}
async function discover(p,q){let hosts=[...new Set(CFG[p].urls.map(x=>new URL(x).hostname))],site=hosts.map(x=>'site:'+x).join(' OR '),term=`(${site}) "${CFG[p].name}" (上線 OR 上架 OR 首播 OR 開播 OR 定檔 OR 熱播) (影集 OR 戲劇 OR 綜藝)`,urls=[];for(let suffix of ['',` ${q.start} ${q.end}`]){try{let h=await get('https://www.bing.com/search?setlang=zh-hant&cc=TW&count=30&q='+encodeURIComponent(term+suffix));urls.push(...bingLinks(h,hosts))}catch{}}return[...new Set(urls)].slice(0,10)}
function merge(a){let m=new Map();for(let x of a){if(!x||!x.title||!x.release_date)continue;let k=`${x.platform}|${x.title}|${x.release_date}`,o=m.get(k);if(!o)m.set(k,x);else o.evidence=[...(o.evidence||[]),...(x.evidence||[])].filter((e,i,z)=>z.findIndex(v=>v.url===e.url)===i)}return[...m.values()]}
async function readPage(env,p,u){try{let h=await get(u);if(strip(h).length<700){let r=await render(env,u);if(r)h=r}return{items:parsePage(p,u,h),links:pageLinks(u,h),ok:true}}catch{return{items:[],links:[],ok:false}}}
async function refresh(env,query='近30天'){let q=range(query),fresh=[],health=[];for(let p of PLATFORMS){let urls=new Set(CFG[p].urls),ok=0,found=0;for(let u of await discover(p,q))urls.add(u);let first=[...urls].slice(0,16),more=new Set();for(let u of first){let r=await readPage(env,p,u);if(r.ok)ok++;fresh.push(...r.items);r.links.forEach(x=>more.add(x))}for(let u of [...more].slice(0,8)){let r=await readPage(env,p,u);if(r.ok)ok++;fresh.push(...r.items)}found=fresh.filter(x=>x.platform===p).length;health.push({platform:p,status:ok?'ok':'error',pages_checked:first.length+Math.min(8,more.size),verified:found})}
let items=merge(fresh);let payload={schema_version:4,updated_at:new Date().toISOString(),last_query:query,query_range:q,stats:{verified:items.length,pending:0},source_health:health,items};await env.OTT_DATA.put('releases',JSON.stringify(payload));return payload}
export default{async fetch(req,env,ctx){let u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-headers':'content-type'}});if(u.pathname==='/api/feed')return J(await env.OTT_DATA.get('releases','json')||{schema_version:4,updated_at:null,query_range:range(),stats:{verified:0,pending:0},source_health:[],items:[]});if(u.pathname==='/api/refresh'&&req.method==='POST'){let b={};try{b=await req.json()}catch{}let q=String(b.query||'近30天');ctx.waitUntil(refresh(env,q));return J({queued:true,query:q},202)}if(u.pathname==='/api/health')return J({ok:true,schema_version:4,today:today(),platforms:PLATFORMS,browser:!!env.BROWSER});return env.ASSETS.fetch(req)},async scheduled(e,env,ctx){ctx.waitUntil(refresh(env,'近30天'))}};