const PLATFORMS=['iQIYI','friDay影音','Netflix','Disney+','Hami Video','MyVideo','LINE TV'];
const CFG={
'iQIYI':{name:'愛奇藝台灣站',sites:['https://www.iq.com/newOnline?lang=zh_tw','https://www.iq.com/drama?lang=zh_tw','https://www.iq.com/variety-show?lang=zh_tw']},
'friDay影音':{name:'friDay影音',sites:['https://video.friday.tw/drama','https://video.friday.tw/show']},
'Netflix':{name:'Netflix Taiwan',sites:['https://about.netflix.com/zh_tw/new-to-watch','https://about.netflix.com/zh_tw/newsroom']},
'Disney+':{name:'Disney+ Taiwan',sites:['https://www.disney.com.tw/disneyplus-articles']},
'Hami Video':{name:'Hami Video',sites:['https://hamivideo.hinet.net/index.do']},
'MyVideo':{name:'MyVideo',sites:['https://www.myvideo.net.tw/drama/','https://www.myvideo.net.tw/program/']},
'LINE TV':{name:'LINE TV Taiwan',sites:['https://www.linetv.tw/channel/1','https://www.linetv.tw/channel/2']}
};
const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}});
const fmt=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const today=()=>fmt(new Date());
const add=(s,n)=>{const d=new Date(s+'T12:00:00+08:00');d.setDate(d.getDate()+n);return fmt(d)};
const mon=s=>{const d=new Date(s+'T12:00:00+08:00'),w=d.getDay();return add(s,w===0?-6:1-w)};
function range(v='近30天'){const t=today(),y=t.slice(0,4),s=String(v).trim().replace(/\s+/g,'').replace(/[－—–~至]/g,'～');if(s==='今天')return{start:t,end:t,label:'今天'};if(/^(近|最近)?(30天|一個月|1個月)$/.test(s))return{start:add(t,-29),end:t,label:'近30天'};if(s==='這週'||s==='本週')return{start:mon(t),end:t,label:'這週'};if(s==='上週'){const e=add(mon(t),-1);return{start:add(e,-6),end:e,label:'上週'}}let m=s.match(/^(20\d{2})\/(\d{1,2})\/(\d{1,2})$/);if(m)return{start:`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`,end:t,label:s+'～今天'};m=s.match(/^(\d{1,2})\/(\d{1,2})～(\d{1,2})\/(\d{1,2})$/);if(m)return{start:`${y}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`,end:`${y}-${m[3].padStart(2,'0')}-${m[4].padStart(2,'0')}`,label:s};m=s.match(/^(\d{1,2})\/(\d{1,2})$/);if(m)return{start:`${y}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`,end:t,label:s+'～今天'};return{start:add(t,-29),end:t,label:'近30天'}}
function dec(s=''){return s.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n))}
function strip(h=''){return dec(h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')).trim()}
function title(s=''){s=strip(s);let m=s.match(/[《〈「『]([^》〉」』]{2,50})[》〉」』]/);if(m)return m[1].trim();s=s.replace(/^[#＃]+/,'').replace(/\s*[|｜].*$/,'').replace(/\s+-\s+.*$/,'').trim();return s.length>=2&&s.length<=45?s:''}
function dateOf(s,year=today().slice(0,4)){const V='上線|上架|首播|開播|播出|登場|定檔|全集上線|正式上線|正式開播|開更|更新';let m=s.match(new RegExp('(20\\d{2})[年/.\\-](\\d{1,2})[月/.\\-](\\d{1,2})日?[^。！？]{0,50}('+V+')'));if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=s.match(new RegExp('(\\d{1,2})[月/.\\-](\\d{1,2})日?[^。！？]{0,50}('+V+')'));if(m)return`${year}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;m=s.match(new RegExp('('+V+')[^。！？]{0,40}(20\\d{2})[年/.\\-](\\d{1,2})[月/.\\-](\\d{1,2})日?'));if(m)return`${m[2]}-${m[3].padStart(2,'0')}-${m[4].padStart(2,'0')}`;m=s.match(new RegExp('('+V+')[^。！？]{0,40}(\\d{1,2})[月/.\\-](\\d{1,2})日?'));return m?`${year}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:null}
function typeOf(s){if(/綜藝|實境|真人秀|選秀|variety|reality/i.test(s))return'綜藝';if(/影集|戲劇|劇集|陸劇|韓劇|台劇|日劇|美劇|series|drama|連續劇/i.test(s))return'戲劇';return''}
const allowed=s=>!/電影|動畫|動漫|短劇|微短劇|紀錄片|演唱會|直播|特輯|體育|賽事|遊戲|電影版/i.test(s);
function excl(s){if(/獨家專訪|獨家花絮|獨家預告|獨家片段|VIP.{0,8}獨家.{0,8}搶先看/i.test(s))return'';const m=s.match(/全台獨家|全網獨播|全網獨家|獨家播出|獨家上線|Only on\s+[^。！？,，]{1,30}|Exclusive\s+on\s+[^。！？,，]{1,30}|僅在[^。！？,，]{1,20}(?:播出|上線)/i);return m?m[0]:''}
function pub(html){const m=html.match(/(?:article:published_time|datePublished)[^>]{0,140}(?:content=|:)["']?([^"'<>,} ]{8,35})/i);return m?m[1]:null}
function item(p,t,d,ty,u,text,kind,published,verifiedSource=true){const claim=excl(text),ok=!!(verifiedSource&&t&&d&&ty&&allowed(t+' '+text));return{id:`${p}-${encodeURIComponent(t||'candidate')}-${d||'pending'}`,title:t||'未辨識作品',platform:p,content_type:ty||'未分類',region:'台灣',release_date:d,release_kind:'上架',episode_info:'',exclusive_status:claim?'true':'unknown',exclusive_claim_text:claim,verification_status:ok?'verified':'pending',verification_method:ok?'official_explicit':'candidate',source_label:`${p} ${kind==='social'?'官方社群':'官方網站'}`,source_url:u,source_published_at:published||null,fetched_at:new Date().toISOString(),review_note:ok?'官方來源明確包含作品、類型與上線日期。':'候選資料，證據不足，不列入正式資料。',evidence:[{kind,label:`${p} ${kind==='social'?'官方社群':'官方網站'}`,url:u,release_date:d,claim_text:text.slice(0,500)}]}}
function pageItem(p,u,h,kind='website'){const text=strip(h),og=h.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)||h.match(/<title[^>]*>([\s\S]*?)<\/title>/i),t=og?title(og[1]):'',d=dateOf(text),ty=typeOf(text);if(!t||!allowed(t+' '+text)||(!d&&!ty))return[];if(/獲獎|入圍|提名|排行榜|記者會|專訪/.test(t)&&!d)return[];return[item(p,t,d,ty,u,text,kind,pub(h),true)]}
function links(base,h){const out=new Set(),re=/<a\b[^>]*href=["']([^"']+)["']/gi;let m;while((m=re.exec(h))){try{const u=new URL(dec(m[1]),base),b=new URL(base);if(u.hostname===b.hostname&&/\/news\/|\/article|\/program|\/drama|\/show|\/detail|\/content/i.test(u.pathname))out.add(u.href)}catch{}}return[...out].slice(0,10)}
function socials(h){const out=new Set(),re=/https?:\/\/(?:www\.)?(?:facebook\.com|instagram\.com)\/[^"'<>\s?#]+/gi;let m;while((m=re.exec(h))){const u=dec(m[0]).replace(/\/$/,'');if(!/share|sharer|login|help|business|privacy|terms/i.test(u))out.add(u)}return[...out].slice(0,8)}
async function get(u){const r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36','accept-language':'zh-TW,zh;q=0.9,en;q=0.5'}});if(!r.ok)throw Error(String(r.status));return r.text()}
async function render(env,u){if(!env.BROWSER)return'';try{const r=await env.BROWSER.quickAction('content',{url:u,gotoOptions:{waitUntil:'domcontentloaded',timeout:12000}});return await r.text()}catch{return''}}
function searchResults(p,h,official){const out=[],re=/<li[^>]+class=["'][^"']*b_algo[^"']*["'][\s\S]*?<h2[^>]*>\s*<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>[\s\S]*?<\/li>/gi;let m;while((m=re.exec(h))){const u=dec(m[1]),text=strip(m[0]);if(!/facebook\.com|instagram\.com/i.test(u))continue;const profile=official.find(x=>u.toLowerCase().startsWith(x.toLowerCase()));if(!profile)continue;const t=title(text),d=dateOf(text),ty=typeOf(text);if(t&&allowed(t+' '+text)&&(d||ty))out.push(item(p,t,d,ty,u,text,'social',null,true))}return out}
async function searchSocial(p,official,qrange){if(!official.length)return[];const terms=official.map(u=>`site:${new URL(u).hostname}${new URL(u).pathname}`).join(' OR ');const q=`(${terms}) (${CFG[p].name}) (上線 OR 上架 OR 首播 OR 開播 OR 播出 OR 定檔) (影集 OR 戲劇 OR 綜藝) ${qrange.start}..${qrange.end}`;for(const host of ['https://www.bing.com/search?setlang=zh-hant&cc=TW&count=50&q=','https://cn.bing.com/search?setlang=zh-hant&cc=TW&count=50&q=']){try{const h=await get(host+encodeURIComponent(q)),a=searchResults(p,h,official);if(a.length)return a}catch{}}return[]}
function merge(a){const m=new Map();for(const x of a){if(!x||!x.title)continue;const k=`${x.platform}|${x.title}|${x.release_date||'pending'}`,o=m.get(k);if(!o){m.set(k,x);continue}o.evidence=[...(o.evidence||[]),...(x.evidence||[])].filter((e,i,z)=>z.findIndex(v=>v.url===e.url&&v.claim_text===e.claim_text)===i);if(x.verification_status==='verified'&&o.verification_status!=='verified')m.set(k,{...x,evidence:o.evidence})}return[...m.values()]}
async function refresh(env,query='近30天'){const q=range(query),old=await env.OTT_DATA.get('releases','json')||{items:[]},fresh=[],health=[];for(const p of PLATFORMS){const official=new Set(),detail=new Set();let err=0,browser=0;for(const u of CFG[p].sites){try{let h=await get(u);if(strip(h).length<800){const rh=await render(env,u);if(rh){h=rh;browser++}}socials(h).forEach(x=>official.add(x));links(u,h).forEach(x=>detail.add(x));fresh.push(...pageItem(p,u,h))}catch{err++}}for(const u of [...detail].slice(0,8)){try{let h=await get(u);if(strip(h).length<800){const rh=await render(env,u);if(rh){h=rh;browser++}}fresh.push(...pageItem(p,u,h))}catch{}}const social=await searchSocial(p,[...official],q);fresh.push(...social);const mine=fresh.filter(x=>x.platform===p);health.push({platform:p,status:err===CFG[p].sites.length?'error':err?'partial':'ok',verified:mine.filter(x=>x.verification_status==='verified').length,pending:mine.filter(x=>x.verification_status!=='verified').length,official_social_profiles:official.size,social_search_hits:social.length,browser_pages:browser})}
const keep=(old.items||[]).filter(x=>x.verification_status==='verified'),items=merge([...keep,...fresh]);const payload={updated_at:new Date().toISOString(),last_query:query,query_range:q,stats:{verified:items.filter(x=>x.verification_status==='verified').length,pending:items.filter(x=>x.verification_status!=='verified').length},source_health:health,items};await env.OTT_DATA.put('releases',JSON.stringify(payload));return payload}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-headers':'content-type'}});if(u.pathname==='/api/feed')return J(await env.OTT_DATA.get('releases','json')||{updated_at:null,query_range:range('近30天'),stats:{verified:0,pending:0},source_health:[],items:[]});if(u.pathname==='/api/refresh'&&req.method==='POST'){let b={};try{b=await req.json()}catch{}const q=String(b.query||'近30天');ctx.waitUntil(refresh(env,q));return J({queued:true,query:q},202)}if(u.pathname==='/api/health')return J({ok:true,platforms:PLATFORMS,browser:!!env.BROWSER,now:new Date().toISOString()});return env.ASSETS.fetch(req)},async scheduled(e,env,ctx){ctx.waitUntil(refresh(env,'近30天'))}};
