const PLATFORMS=['iQIYI','friDay影音','Netflix','Disney+','Hami Video','MyVideo','LINE TV'];
const SOURCES={
'iQIYI':['https://www.iq.com/newOnline?lang=zh_tw','https://www.iq.com/drama?lang=zh_tw','https://www.iq.com/variety-show?lang=zh_tw'],
'friDay影音':['https://video.friday.tw/drama','https://video.friday.tw/show'],
'Netflix':['https://about.netflix.com/zh_tw/new-to-watch','https://about.netflix.com/zh_tw/newsroom'],
'Disney+':['https://www.disney.com.tw/disneyplus-articles'],
'Hami Video':['https://hamivideo.hinet.net/index.do'],
'MyVideo':['https://www.myvideo.net.tw/drama/','https://www.myvideo.net.tw/program/'],
'LINE TV':['https://www.linetv.tw/channel/1','https://www.linetv.tw/channel/2']};
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const add=(s,n)=>{const d=new Date(s+'T12:00:00+08:00');d.setDate(d.getDate()+n);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)};
const monday=s=>{const d=new Date(s+'T12:00:00+08:00'),w=d.getDay();return add(s,w===0?-6:1-w)};
function range(v='這週'){const t=today(),y=t.slice(0,4),s=String(v).trim().replace(/\s+/g,'').replace(/[－—–~至]/g,'～');if(s==='今天')return{start:t,end:t,label:'今天'};if(/^(近|最近)?(30天|一個月|1個月)$/.test(s))return{start:add(t,-29),end:t,label:'近30天'};if(s==='這週'||s==='本週')return{start:monday(t),end:t,label:'這週'};if(s==='上週'){const e=add(monday(t),-1);return{start:add(e,-6),end:e,label:'上週'}};let m=s.match(/^(\d{1,2})\/(\d{1,2})～(\d{1,2})\/(\d{1,2})$/);if(m)return{start:`${y}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`,end:`${y}-${m[3].padStart(2,'0')}-${m[4].padStart(2,'0')}`,label:s};m=s.match(/^(\d{1,2})\/(\d{1,2})$/);if(m)return{start:`${y}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`,end:t,label:s+'～今天'};return{start:monday(t),end:t,label:'這週'}}
function strip(h=''){return h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&amp;/g,' ').replace(/\s+/g,' ').trim()}
function explicitDate(s,year){let m=s.match(/(20\d{2})[年/.\-](\d{1,2})[月/.\-](\d{1,2})日?[^。！？]{0,35}(上線|上架|首播|開播|播出|登場|定檔)/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=s.match(/(\d{1,2})[月/.\-](\d{1,2})日?[^。！？]{0,35}(上線|上架|首播|開播|播出|登場|定檔)/);return m?`${year}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`:null}
function typeOf(s){if(/綜藝|實境|真人秀|選秀|variety|reality/i.test(s))return'綜藝';if(/影集|戲劇|劇集|陸劇|韓劇|台劇|日劇|美劇|series|drama/i.test(s))return'戲劇';return''}
function allowed(s){return !/電影|動畫|動漫|短劇|微短劇|紀錄片|演唱會|直播|特輯|體育|賽事|遊戲/i.test(s)}
function parse(platform,url,html){const s=strip(html),year=today().slice(0,4),out=[],re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){let title=strip(m[2]).replace(/立即觀看|線上看|播放|更多|詳情|預告|即將上線|新上架/g,'').trim();if(title.length<2||title.length>70)continue;const around=strip(html.slice(Math.max(0,m.index-400),Math.min(html.length,re.lastIndex+400))),date=explicitDate(around,year),type=typeOf(around);if(!date||!type||!allowed(title+' '+around))continue;if(/獲獎|入圍|提名|排行榜|記者會/.test(title)&&!/定檔|上線|首播/.test(around))continue;let href=m[1];try{href=new URL(href,url).href}catch{}out.push({id:`${platform}-${encodeURIComponent(title)}-${date}`,title,platform,content_type:type,region:'台灣',release_date:date,release_kind:'上架',episode_info:'',exclusive_status:/全台獨家|全網獨播|全網獨家|獨家播出|獨家上線|only on|exclusive/i.test(around)?'true':'unknown',exclusive_claim_text:'',verification_status:'verified',verification_method:'official_explicit',source_label:`${platform} 官方網站`,source_url:href,source_published_at:null,fetched_at:new Date().toISOString(),review_note:'官方來源明確連結作品、類型與上線日期。',evidence:[{kind:'website',label:`${platform} 官方網站`,url:href,release_date:date,claim_text:around.slice(0,220)}]})}return out}
async function refresh(env,query='近30天'){const old=await env.OTT_DATA.get('releases','json')||{items:[]},health=[],fresh=[];for(const p of PLATFORMS){let v=0,err=0;for(const u of SOURCES[p]){try{const r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0','accept-language':'zh-TW,zh;q=0.9'}});if(!r.ok){err++;continue}const a=parse(p,u,await r.text());v+=a.length;fresh.push(...a)}catch{err++}}health.push({platform:p,status:err===SOURCES[p].length?'error':err?'partial':'ok',verified:v,sources:SOURCES[p].length})}const map=new Map();for(const x of [...(old.items||[]),...fresh])if(x.verification_status==='verified')map.set(`${x.platform}|${x.title}|${x.release_date}`,x);const items=[...map.values()],q=range(query),payload={updated_at:new Date().toISOString(),last_query:query,query_range:q,stats:{verified:items.length,pending:0},source_health:health,items};await env.OTT_DATA.put('releases',JSON.stringify(payload));return payload}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-headers':'content-type'}});if(u.pathname==='/api/feed'){const d=await env.OTT_DATA.get('releases','json');return json(d||{updated_at:null,query_range:range('這週'),stats:{verified:0,pending:0},source_health:[],items:[]})}if(u.pathname==='/api/refresh'&&req.method==='POST'){let b={};try{b=await req.json()}catch{}const q=String(b.query||'近30天');ctx.waitUntil(refresh(env,q));return json({queued:true,query:q},202)}if(u.pathname==='/api/health')return json({ok:true,platforms:PLATFORMS,now:new Date().toISOString()});return json({error:'not found'},404)},async scheduled(event,env,ctx){ctx.waitUntil(refresh(env,'近30天'))}};